name: Run Behave Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Repositoriyni yuklash
      uses: actions/checkout@v3

    - name: Pythonni o‘rnatish
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Chrome o‘rnatish
      run: |
       sudo apt-get update
       sudo apt-get install -y wget unzip xvfb libxi6 libnss3 libxss1 libgtk-3-0 libdbus-glib-1-2
       wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
       sudo dpkg -i google-chrome*.deb || sudo apt-get -f install -y


    - name: Kutubxonalarni o‘rnatish
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: .env faylni yaratish (Secrets orqali)
      env:
        HEADLESS: true
        LOGIN_URL: ${{ secrets.LOGIN_URL }}
        PHONE: ${{ secrets.PHONE }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        echo "HEADLESS=$HEADLESS" >> .env
        echo "LOGIN_URL=$LOGIN_URL" >> .env
        echo "PHONE=$PHONE" >> .env
        echo "PASSWORD=$PASSWORD" >> .env

    - name: Behave testlarini html report bilan ishga tushurish
      run: |
        mkdir -p reports
        behave -f behave_html_formatter:HTMLFormatter -o reports/report.html

    - name: HTML reportni saqlash
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: behave-html-report
        path: reports/report.html
